blog_app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

blog_app/main/routes.py
from flask import Blueprint
from flask import render_template, request, Blueprint
from blog_app.models import Post

main = Blueprint('main', __name__)

@main.route('/')
def home():
    page=request.args.get('page',1,type=int)
    posts=Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template('home.html',posts=posts)


@main.route('/weather',methods=['GET','POST'])
def weather():
    return render_template('weather.html')   

@main.route('/news',methods=['GET','POST'])
def news():
    return render_template('news.html') 

@main.route('/calender')
def calender():
    return render_template('calender.html')

@main.route('/about')
def about():
    return render_template('about.html')      

blog_app/posts/routes.py
from flask import Blueprint
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from blog_app import db
from blog_app.models import Post
from blog_app.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route('/post/new',methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='New Post', form=form,legend='New Post')

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route("/post/<int:post_id>/update",methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title=form.title.data
        post.content=form.content.data
        db.session.commit()
        flash("Your post has been updated!", 'success')
        return redirect(url_for('posts.post',post_id=post.id))
    elif request.method =='GET':
        form.title.data=post.title
        form.content.data=post.content
    return render_template('create_post.html',title='Update Post', form=form,legend='Update Post')

@posts.route("/post/<int:post_id>/delete",methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", 'success')
    return redirect(url_for('main.home')) 

blog_app/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from blog_app import db, bcrypt
from blog_app.models import User, Post
from blog_app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from blog_app.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route('/signin',methods=['POST', 'GET'])
def signin():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created!, You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('signin.html', title='Register', form=form)


@users.route("/login",methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page=request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html',title='LogIN',form=form)

@users.route('/account',methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file=save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username=form.username.data
        current_user.email=form.email.data
        db.session.commit()
        flash('Your account has been updated!','success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data=current_user.username
        form.email.data=current_user.email 
    image_file = url_for('static',filename='profile_pics/' + current_user.image_file)
    return render_template('account.html',title='Account', image_file=image_file, form=form)

@users.route('/user/<string:username>')
def user_posts(username):
    page=request.args.get('page',1,type=int)
    user=User.query.filter_by(username=username).first_or_404()
    posts=Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template('user_posts.html',posts=posts,user=user)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/reset_password',methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent with instructions to reset yor password.", 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',title='Reset Password', form =form) 

@users.route('/reset_password/<token>',methods=['GET','POST'])
@login_required
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))    
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password=hashed_password
        db.session.commit()
        flash('Your password has been updated!, You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',title='Reset Password', form =form) 

blog_app/templates/calender.html
{% extends "layout.html" %}
{% block content %}
    <h2 class="centre_content">Calender</h2>
{% endblock %}

blog_app/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
{% for message in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <div class="row justify-content-center">
        <div class="card text-centre align-self-center" style="width: 50%;">
            <div class="col-lg">
                <div class="login-header">
                    <h3>{{legend}}</h3>
                </div>
            </div>
            <div class="col-lg">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <br>
            <div class="col-lg">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <br>
            <div class="col-lg">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <br>
        </div>
    </div>
    <hr>
</form>
{% endblock %}

blog_app/templates/home.html
{% extends "layout.html" %}
{% block content %}
<!-- {% for message in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{message}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %} -->
<article>
  {% for post in posts.items %}
  <!-- <div class="card border-info mb-3"  style="max-width: 540px;">
        <img class="rounded-circle article-image" style="max-width: 120px;"
            src="{{url_for('static',filename='profile_pics/'+post.author.image_file)}}">

        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted }}</small>
                </div>
                <h5 class="card-title">
                    <a class="article-title" href="#">{{ post.title }}</a>
                </h5>
                <div class="card-body">
                    <p class="article-content">{{ post.content }}</p>
                </div>

            </div>
        </article>
    </div> -->
  <div class="row justify-content-center">
    <div class="card mb-3" style="max-width: auto;max-height:auto;">
      <div class="row g-0">
        <div class="col">
          <img class="img-fluid rounded-circle  mt-3"
            src="{{url_for('static',filename='profile_pics/'+post.author.image_file)}}">
        </div>
        <div class="col-10">
          <div class="card-body">
            <a class="mr-2" href="{{url_for('users.user_posts',username=post.author.username)}}">{{ post.author.username
              }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <h5 class="card-title"> <a class="article-title" href="{{url_for('posts.post', post_id = post.id)}}">{{ post.title
                }}</a></h5>
            <p class="card-text">{{ post.content }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- <article class="media content-section">
        <div class="column"><img class="rounded-circle article-image" src="{{url_for('static',filename='profile_pics/'+post.author.image_file)}}"></div>
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          </div>
          <h2><a class="article-title" href="{{url_for('posts.post', post_id = post.id)}}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
      </article> -->

  {% endfor %}
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
  {% if posts.page==page_num %}
  <a class="btn btn-info mb-4 mt-4" href="{{url_for('main.home', page=page_num)}}">{{page_num}}</a>
  {% else %}
  <a class="btn btn-outline-info mb-4 mt-4" href="{{url_for('main.home', page=page_num)}}">{{page_num}}</a>
  {% endif %}
  {% else %}
  ...
  {% endif %}
  {% endfor %}
  {% endblock %}

blog_app/templates/layout.html
<!doctype html>
<html lang="en">
    
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Favicon-->
    <link rel="shortcut icon" href="{{url_for('static',filename='apple-touch-icon.png')}}" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='main.css')}}">
    <title>Hello, world!</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">CodeBlog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{url_for('main.home')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{url_for('main.about')}}">About</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="/price">Pricing</a>
                    </li> -->
                </ul>



                <span class="navbar-text">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{url_for('posts.new_post')}}">New Post</a>
                        </li>
                        <li class="nav-item">

                            <a class="nav-link active" aria-current="page" href="{{url_for('users.account')}}">Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{url_for('users.logout')}}">Log out</a>
                        </li>
                        {% else %}
                        <!-- <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li> -->
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{url_for('users.login')}}">Log in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{url_for('users.signin')}}">Sign in</a>
                        </li>
                        {% endif %}
                    </ul>
                </span>
            </div>
        </div>
    </nav>
    <br />
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">

                    <h3>Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">
                            <a href="{{url_for('main.weather')}}">weather</a>
                        </li>
                        <li class="list-group-item list-group-item-light">
                            <a href="{{url_for('main.news')}}">News</a>
                        </li>
                        <li class="list-group-item list-group-item-light">
                            <a href="{{url_for('main.calender')}}">Calendars</a>
                        </li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>

    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top footer">
            <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    
                    <svg class="bi" width="30" height="24">
                        <use xlink:href="#bootstrap" />
                    </svg>
                </a>
                    
                <span class="text-muted">&copy; 2021 CodeBlog</span>
            </div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <a href="#">Back to top</a>
                <li class="ms-3"><a class="text-muted" href="#"></a></li>
                <li class="ms-3"><a class="text-muted" href="#"></a></li>
                <li class="ms-3"><a class="text-muted" href="#"></a></li>
            </ul>
        </footer>
    </div>

    <!-- <div class="card text-center">
        <div class="card-header">
            <nav aria-label="...">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">2</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
        </div> 
        <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
        <div class="card-footer text-muted">
            2 days ago
        </div>
    </div> -->




    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
</body>

</html>

blog_app/templates/login.html
{% extends "layout.html" %}
{% block content %}
<!-- {% for message in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% endfor %} -->

{% if email %}
<h2>hello {{email}}</h2>
{% else %}
<!-- <h6>nooooooo!</h6> -->
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <div class="row justify-content-center">
    <div class="card text-centre align-self-center" style="width: 50%;">
        <div class="col-lg">
            <div class="login-header">
                <h3>Log in</h3>
                <p >Please enter your credentials to login.</p>
            </div>
        </div>
        <div class="col-lg">
            <!-- {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control") }} -->
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <br>
        <div class="col-lg">
            <!-- {{ form.password.label(class="form-label") }}
            {{ form.password(class="form-control") }} -->
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
            {{ form.password(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <br>
        <div class="col-lg">
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        <small class="text-muted ml-2"><a href="{{url_for('users.reset_request')}}">Forgot password?</a></small>
        <small class="text-muted">Need an account?  <a href="{{url_for('users.signin')}}">Sign up now</a></small>
    </div>
    </div>
    <hr>
</form>
{% endif %}
{% endblock %}

blog_app/templates/news.html
{% extends "layout.html" %}
{% block content %}
    <h2 class="centre_content">News</h2>
{% endblock %}

blog_app/templates/post.html
{% extends "layout.html" %}
{% block content %}
<!-- {% for message in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %} -->
<!-- <article>    
    <article class="media content-section">
        <img class="rounded-circle article-image" src="{{url_for('static',filename='profile_pics/'+post.author.image_file)}}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          </div>
          <h2 class="article-title">{{ post.title }}</h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
      </article> -->

<div class="card mb-3" style="max-width: 740px;">
    <article>
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{url_for('static',filename='profile_pics/'+post.author.image_file)}}"
                    class="img-fluid rounded-circle m-3 mt-3"  width="50%" height="50%"  alt="...">
            </div>
            <div class="col-md-8 mt-2">
                <a class="mr-2 " href="{{url_for('users.user_posts',username=post.author.username)}}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.update_post', post_id=post.id)}}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal"
                        data-bs-target="#deleteModal">Delete</button>
                </div>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content }}</p>
                    <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
                </div>
            </div>
        </div>
    </article>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{url_for('posts.delete_post', post_id=post.id)}}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

<!-- <div class="card border-info mb-3">
                <img class="rounded-circle article-image" src="{{url_for('static',filename='profile_pics/'+post.author.image_file)}}">
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h5 class="card-title">
                    <a class="article-title" href="#">{{ post.title }}</a>
                </h5>
                <div class="card-body">
                    <p class="article-content">{{ post.content }}</p>
                </div>

            </div>
        </article>
        
    </div> -->


{% endblock %}

blog_app/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
<!-- {% for message in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% endfor %} -->

{% if email %}
<h2>hello {{email}}</h2>
{% else %}
<!-- <h6>nooooooo!</h6> -->
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <div class="row justify-content-center">
    <div class="card text-centre align-self-center" style="width: 50%;">
        <div class="col-lg">
            <div class="login-header">
                <h3>Reset Password</h3>
            </div>
        </div>
        <div class="col-lg">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <br>
        <div class="col-lg">

            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </div>
    </div>
    <hr>
</form>
{% endif %}
{% endblock %}

blog_app/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}

<h1 class="mb-3">Post by {{user.username}} ({{posts.total}})</h1>
<article>
    {% for post in posts.items %}
    <div class="row justify-content-center">
        <div class="card mb-3" style="max-width: 1000px;max-height:auto;">
            <div class="row g-0">
                <div class="col">
                    <img class="img-fluid rounded-circle mt-3"
                     src="{{url_for('static',filename='profile_pics/'+post.author.image_file)}}">
                </div>
                <div class="col-10">
                    <div class="card-body">
                        <a class="mr-2" href="{{url_for('users.user_posts',username=post.author.username)}}">{{
                            post.author.username }}</a>
                        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                        <h5 class="card-title"> <a class="article-title"
                                href="{{url_for('posts.post', post_id = post.id)}}">{{ post.title }}</a></h5>
                        <p class="card-text">{{ post.content }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
    {% if posts.page==page_num %}
    <a class="btn btn-info mb-4 mt-4"
        href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}}</a>
    {% else %}
    <a class="btn btn-outline-info mb-4 mt-4"
        href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
    {% endblock %}

blog_app/templates/weather.html
{% extends "layout.html" %}
{% block content %}
<section>
    <h1 class="centre_content" >Check Weather
    </h1>
    <form action="" method="post">
        <label for="1"></label>
        <input class="centre_content" type="text" placeholder="Search for a city" autofocus autocomplete="off"><br><br>
        <button class="centre_content rounded-pill btn-primary" type="submit">Submit</button>
    </form>
   </section>
{% endblock %}